# workflow name
name: tests-payments
# determine when to run this workflow
on:
  pull_request
# specify the events that you want to run on the pull req
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
